### ISSUE TITLE
Sometimes the tool crashes when the account still has CPU, but the tool reports that the CPU is overloaded on Wax. Forever loop

### ISSUE THREAD

**Issue by studiobummbum** [encoderlee/OpenAlien#1]
Sometimes the tool crashes when the account still has CPU, but the tool reports that the CPU is overloaded on Wax. Forever loop. Can you check on it ?

**Comment by encoderlee** [comment]
What is the error message? 
if the error message is 
>estimated CPU time (0 us) is not less than the maximum billable CPU time for the transaction (0 us)

it means you have been blocked by wax rpc node, because you submitted too many wrong transactions.
you can see:
[https://forums.eoscommunity.org/t/error-estimated-cpu-time-0-us-is-not-less-than-the-maximum-billable-cpu-time-for-the-transaction-0-us/5780](https://forums.eoscommunity.org/t/error-estimated-cpu-time-0-us-is-not-less-than-the-maximum-billable-cpu-time-for-the-transaction-0-us/5780)
change wax node rpc host or wait 24 hours

**Comment by studiobummbum** [comment]
I no longer have that case. Thank you. But there is also another problem that the tool seems to be stopped and not running regularly. For example, I have a mining command at 10:00:00 but the tool only stops at 10:00:00 without continuing. Or do I have to configure something?

**Comment by encoderlee** [comment]
check log files in 'logs' folder, if it stop without any error,  it may be caused by cmd.exe's quick edit mode.
you can use cmder ([https://github.com/cmderdev/cmder](https://github.com/cmderdev/cmder))  to run python instead of cmd.exe
